import "./test/pathnameCanContainsMetaMatching/pathnameCanContainsMetaMatching.test.js"
import "./test/pathnameToMeta/anyFolder.test.js"
import "./test/pathnameToMeta/basic.test.js"
import "./test/pathnameToMeta/complex.test.js"
import "./test/pathnameToMeta/wildcard.test.js"
import "./test/selectAllFileInsideFolder/selectAllFileInsideFolder.test.js"
